apiVersion: v1
kind: ServiceAccount
metadata:
  name: kcloud-cost-estimator
  namespace: kcloud-system
  labels:
    app: kcloud-cost-estimator
    app.kubernetes.io/name: kcloud-cost-estimator
    app.kubernetes.io/component: collector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kcloud-cost-estimator
  labels:
    app: kcloud-cost-estimator
    app.kubernetes.io/name: kcloud-cost-estimator
    app.kubernetes.io/component: collector
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/stats
  - pods
  - namespaces
  verbs: ["get", "list", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources:
  - nodes
  - pods
  verbs: ["get", "list"]
- apiGroups: [""]
  resources:
  - services
  - endpoints
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
  resourceNames:
  - kcloud-cost-estimator-config
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kcloud-cost-estimator
  labels:
    app: kcloud-cost-estimator
    app.kubernetes.io/name: kcloud-cost-estimator
    app.kubernetes.io/component: collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kcloud-cost-estimator
subjects:
- kind: ServiceAccount
  name: kcloud-cost-estimator
  namespace: kcloud-system
